### PR TITLE
[IMP] transfer analytic account and cost center to spread

### PR DESCRIPTION
**Pull request by hbrunn**
@astirpe I've got a few things to add (some extra checks to avoid users shooting themselves in the foot, undo spread, recalculate lines, ...) - do you prefer one PR per feature or one that lumps everything together?

### CODE REVIEW

**Comment by astirpe** [comment]
@hbrunn thank you! One PR containing a lump of features is fine.

**Comment by hbrunn** [comment]
@astirpe that's it for now. The checks I talked about are quite idiosyncratic for my current customer, so no use putting them here. If you like, review makes sense now

**Comment by hbrunn** [comment]
the last commit might be a bit dubious: The fields I recycle here don't seem to be used, is this roughly what you had in mind?

**Comment by astirpe** [comment]
@hbrunn The fields `remaining_amount` and `spreaded_amount ` are not used indeed, they could be removed or maybe displayed in the view. The code of [account_cost_spread V10](https://github.com/onesteinbv/addons-onestein/blob/10.0/account_cost_spread/) was a lot cleaned up while porting to V10, but it would need some other improvements. I will merge your changes also in V10.

I'm looking at your changes, thanks again!

**Pull request merged**
